import {HospitalRecord} from './hospital_record';

export const HOSPITAL_RECORDS: HospitalRecord[] = [
  {
    id: 1,
    pandemicType: 'COVID19',
    availableCount: 5,
    notifyWhenUserSubscribe: true,
    floor: '2',
    section: 'N/A',
    room: '210',
    itemType: 'Bed',
    itemCount: 10,
    itemName: 'Semi-Private Bed',
    itemId: '210-B1',
    note: 'Available',
    isAvailable: true,
    availableFrom: '31-05-2020',
    availableTill: '02-06-2020',
    hospitalRegistration: {
      id: 1,
      name: 'Hospital 01',
      hospitalId: 'HOSPITAL001',
      phone: '423423423',
      emailId: 'dummy@example.com',
      addressDetails: '1/2, CP, Delhi, 110001',
      city: 'Delhi',
      zipCode: '110001',
      latitude: 28.2131,
      longitude: 80.121
    }
  },
  {
    id: 2,
    pandemicType: 'COVID19',
    availableCount: 5,
    notifyWhenUserSubscribe: true,
    floor: '2',
    section: 'N/A',
    room: '210',
    itemType: 'Ventilator',
    itemCount: 10,
    itemName: 'Oxygen Ventilator',
    itemId: '210-B1',
    note: 'Available',
    isAvailable: true,
    availableFrom: '31-05-2020',
    availableTill: '02-06-2020',
    hospitalRegistration: {
      id: 1,
      name: 'Hospital 02',
      hospitalId: 'HOSPITAL002',
      phone: '423423423',
      emailId: 'dummy@example.com',
      addressDetails: '1/2, CP, Delhi, 110001',
      city: 'Delhi',
      zipCode: '110001',
      latitude: 28.2131,
      longitude: 80.121
    }
  },
  {
    id: 3,
    pandemicType: 'COVID19',
    availableCount: 5,
    notifyWhenUserSubscribe: true,
    floor: '2',
    section: 'N/A',
    room: '210',
    itemType: 'Bed',
    itemCount: 10,
    itemName: 'Semi-Private Bed',
    itemId: '210-B1',
    note: 'Available',
    isAvailable: true,
    availableFrom: '31-05-2020',
    availableTill: '02-06-2020',
    hospitalRegistration: {
      id: 1,
      name: 'Hospital 03',
      hospitalId: 'HOSPITAL003',
      phone: '423423423',
      emailId: 'dummy@example.com',
      addressDetails: '1/2, CP, Delhi, 110001',
      city: 'Delhi',
      zipCode: '110001',
      latitude: 28.2131,
      longitude: 80.121
    }
  }
];