import {HospitalRecord} from './hospital_record';

export const HOSPITAL_RECORDS: HospitalRecord[] = [
  {
    id: 1,
    hospitalId: 'HOSPITAL001',
    name: 'Hospital 01',
    phone: '423423423',
    email: 'dummy@example.com',
    notifyWhenUserSubscribe: true,
    address: '1/2, CP, Delhi, 110001',
    floor: '2',
    section: 'N/A',
    room: '210',
    itemType: 'Bed',
    itemCount: 10,
    itemName: 'Semi-Private Bed',
    itemId: '210-B1',
    note: 'Available',
    isAvailable: true,
    availableFrom: '31-05-2020',
    availableTill: '02-06-2020'
  },
  {
    id: 2,
    hospitalId: 'HOSPITAL002',
    name: 'Hospital 02',
    phone: '423423422',
    email: 'dummy@example.com',
    notifyWhenUserSubscribe: true,
    address: '1/2, CP, Delhi, 110002',
    floor: '2',
    section: 'N/A',
    room: '210',
    itemType: 'Bed',
    itemCount: 10,
    itemName: 'Semi-Private Bed',
    itemId: '210-B1',
    note: 'Available',
    isAvailable: false,
    availableFrom: '31-05-2020',
    availableTill: '02-06-2020'
  },
  {
    id: 3,
    hospitalId: 'HOSPITAL003',
    name: 'Hospital 03',
    phone: '423423421',
    email: 'dummy@example.com',
    notifyWhenUserSubscribe: true,
    address: '1/2, CP, Delhi, 110003',
    floor: '2',
    section: 'N/A',
    room: '210',
    itemType: 'Bed',
    itemCount: 10,
    itemName: 'Semi-Private Bed',
    itemId: '210-B3',
    note: 'Available',
    isAvailable: true,
    availableFrom: '31-05-2020',
    availableTill: '02-06-2020'
  }
];